# Generated by Django 5.0 on 2023-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_chatroom_isagent_message_isagent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="isAgent",
            new_name="is_agent",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
