# Generated by Django 5.0 on 2023-12-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_rename_isagent_message_is_agent_chatroom_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
