# Generated by Django 5.0 on 2023-12-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_message_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={"ordering": ("-created_at",)},
        ),
    ]
