# Generated by Django 5.0 on 2023-12-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Full Name"
            ),
        ),
    ]
