# Generated by Django 5.0 on 2023-12-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_chatuser_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatuser",
            name="designation",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Designation",
            ),
        ),
        migrations.AddField(
            model_name="chatuser",
            name="need_password_change",
            field=models.BooleanField(default=True),
        ),
    ]
