# Generated by Django 5.0 on 2023-12-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_chatuser_designation_chatuser_need_password_change"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatuser",
            options={
                "ordering": ["-timestamp"],
                "permissions": [
                    ("custom_profile_delete_users", "Can delete  users"),
                    ("custom_profile_add_users", "Can add  users"),
                    ("custom_profile_view_users", "Can view  users"),
                    ("custom_profile_edit_users", "Can edit  users"),
                ],
            },
        ),
    ]
