# Generated by Django 5.0 on 2023-12-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_chatuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatuser",
            name="designation",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Designation"
            ),
        ),
    ]
